git:
  depth: 3

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

    - os: osx
      osx_image: xcode7.3
      sudo: required

addons:
  apt:
    packages:
      - llvm-3.6-dev
      - libedit-dev
      - flex
      - bison

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm flex bison; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh ./scripts/fix_ubuntu_llvm.sh; fi
  - sudo sh ./scripts/install_gtest.sh
  - sudo sh ./scripts/chmod_runnable.sh

script:
  - make test
  - python ./EliteTest/full_test/run_test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
