dist: trusty
language: cpp
git:
  depth: 3

install:
  - sudo apt-get update
  - sudo apt-get install -y llvm-3.6-dev libglibmm-2.4-dev libedit-dev flex bison 
  - sudo sh ./scripts/fix_ubuntu_llvm.sh

script:
  - make test

