dist: trusty
language: cpp
git:
  depth: 3

install:
  - sudo apt-get update
  - sudo apt-get install -y llvm-3.6-dev libedit-dev flex bison
  - sudo sh ./scripts/fix_ubuntu_llvm.sh
  - sudo sh ./scripts/install_gtest.sh
  - sudo sh ./scripts/chmod_runnable.sh
  - pip install --user codecov

script:
  - make test
  - python ./EliteTest/full_test/run_test.py

after_success:
  - codecov

