platform:
  - x86

configuration:
  - Release

install:
  - scripts\install_llvm_win32.bat

build:
  - mkdir build
  - cd build
  - cmake -DLLVM_SDK_PATH="C:/projects/elite/LLVM_SDK" -DLLVM_VERSION=3.7 ..
  - msbuild /p:Configuration=Release "deps.vcxproj"
  - msbuild /p:Configuration=Release "elite.vcxproj"
